version: 0.2

# AWS CodeBuild Batch configuration
# https://docs.aws.amazon.com/codebuild/latest/userguide/batch-build-buildspec.html
# Define 5 parallel builds to run using the "build-matrix"
build-matrix:
    static:
      ignore-failure: false
      env:
        type: LINUX_CONTAINER
    dynamic:
      env:
        variables:
          WORKERS:
            - 1
            - 2
            - 3
            - 4
            - 5
        # Optional: Use Custom Public ECR Image as container
        #image:
        #  - public.ecr.aws/your-namespace/image-name
